global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus monitorando ele mesmo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitoramento HTTP(S) via Blackbox Exporter
  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [https_2xx_ssl]
    scrape_interval: 15s
    static_configs:
      - targets:
          - api.xpto.com.br
          - api-b.xpto.com.br
          - portal.xpto.com.br
          - guia.xpto.com.br
          - cultura.xpto.com.br
          - relatorio.xpto.com.br
          - port.xpto.com.br
          - marca.xpto.com.br
          - des.xpto.com.br
          - inter.xpto.com.br
          - ouv.xpto.com.br
          - ben.xpto.com.br
          - api-v.xpto.com.br
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

