global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://portaldocooperado.unimednatal.com.br/
          - https://guiamedico.unimednatal.com.br/
          - https://cultural.unimednatal.com.br/
          - https://relatoriodegestao.unimednatal.com.br/
          - https://portaldopaciente.unimednatal.com.br/
          - https://marcacaodeconsultas.unimednatal.com.br/
          - https://despesas.unimednatal.com.br/
          - https://intercambio.unimednatal.com.br/
          - https://ouvidoria.unimednatal.com.br/
          - https://beneficiario.unimednatal.com.br/
          - https://api-vendas.unimednatal.com.br/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
