global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus monitorando ele mesmo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitoramento HTTP(S) via Blackbox Exporter
  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [https_2xx_ssl]
    scrape_interval: 15s
    static_configs:
      - targets:
          - api-consolemed.unimednatal.com.br
          - api-benef.unimednatal.com.br
          - portaldocooperado.unimednatal.com.br
          - guiamedico.unimednatal.com.br
          - cultural.unimednatal.com.br
          - relatoriodegestao.unimednatal.com.br
          - portaldopaciente.unimednatal.com.br
          - marcacaodeconsultas.unimednatal.com.br
          - despesas.unimednatal.com.br
          - intercambio.unimednatal.com.br
          - ouvidoria.unimednatal.com.br
          - beneficiario.unimednatal.com.br
          - api-vendas.unimednatal.com.br
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

